
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'mtg_datalake'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'mtg_datalake'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  mtg_datalake:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view
    staging:
      +schema: staging 
      +materialized: table
    analytics:
      +schema: analytics
      +materialized: table
    processed:
      +materialized: table
      +schema: processed
      +tags:
        - processed
      moxfield:
        +tags: 
          - moxfield
        pauperedh:
          +tags:
            - pauperedh
        commander:
          +tags:
            - commander
        budget_edh:
          +tags:
            - budget_edh
        historic_brawl:
          +tags:
            - brawl
        cedh:
          +tags:
           - cedh
      scryfall:
        +tags:
          - scryfall
      web_resources:
        +tags:
          - web


      

snapshots:
  mtg_datalake:
    +target_database: "mtg_datalake"
    +target_schema: "mtg_datalake"    
    raw:
      +tags: 
        - raw
      moxfield:
        +tags: 
          - moxfield
        commander:
          +tags:
            - commander
        budget_edh:
          +tags:
            - budget_edh
        pauperedh:
          +tags: 
            - pauperedh
        historic_brawl:
          +tags:
            - brawl
      scryfall:
        +tags:
          - scryfall
      